version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    env_file: ./.env
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ping:1})"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    depends_on:
      mongodb:
        condition: service_healthy
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    container_name: api
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.database=$MONGO_INITDB_DATABASE
      - spring.data.mongodb.password=$MONGO_INITDB_ROOT_PASSWORD
      - spring.data.mongodb.username=$MONGO_INITDB_ROOT_USERNAME
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
